name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: print Java version
      run: java -version
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          maven-${{ runner.os }}-
          maven-
    - name: Build
      run: mvn --no-transfer-progress -B clean verify
    - name: Clean before caching
      run: find ~/.m2 -name "_remote.repositories" | xargs --no-run-if-empty rm
